FROM golang:1.10

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN go get -u github.com/golang/dep/cmd/dep 
COPY ./ /go/src/github.com/admission-webhook-example
RUN cd /go/src/github.com/admission-webhook-example && dep ensure -v
RUN go build -a -installsuffix cgo -o admission-webhook-example && cp admission-webhook-example /admission-webhook-example

ENTRYPOINT ["./admission-webhook-example"]
